bootstrap.servers=localhost:9092
schema.registry.url=http://localhost:8081
key.serializer=org.apache.kafka.common.serialization.StringSerializer
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
topic.name=commentaires
group.id=editeur-commentaires
specific.avro.reader=false