#global
org.slf4j.simpleLogger.defaultLogLevel=info

#kafka
org.slf4j.simpleLogger.log.org.apache.kafka=warn
org.slf4j.simpleLogger.log.io.confluent=warn

#hibernate
org.slf4j.simpleLogger.log.org.hibernate=warn